### ISSUE TITLE
Website is unreachable

### ISSUE THREAD

**Issue by alexandre-mahdhaoui** [gopakumarce/R2#18]
Hi, 

The project is super interesting, however I noticed the r2.rs website is unreachable. What happened to it?

**Comment by gopakumarce** [comment]
Hi @alexandre-mahdhaoui sorry for the late response, the contents in the website are all available here - https://github.com/gopakumarce/R2/tree/master/Docs

**Comment by alexandremahdhaoui** [comment]
Thanks a lot for the heads up.
